version: '3'
services:

  # PHP
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php
    restart: unless-stopped
    tty: true
    working_dir: /var/www/html
    volumes:
      - webdata:/var/www/html
    networks:
      - app-network

  # Web Server
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - webdata:/var/www/html
      - ./nginx/conf.d/app.conf:/etc/nginx/conf.d/app.conf
    networks:
      - app-network

  # MySQL
  mysql:
    image: mysql:5.7.22
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost", '-u', 'root', '-p$$MYSQL_ROOT_PASSWORD' ]
      timeout: 20s
      retries: 10
    environment:
      MYSQL_DATABASE: system
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - app-network

  # Redis
  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    tty: true
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 1s
      timeout: 3s
      retries: 30
    networks:
      - app-network

# Docker Network
networks:
  app-network:
    driver: bridge

# Volumes
volumes:
  dbdata:
    name: docker_web_development_db_data
    driver: local
  webdata:
    name: docker_web_development_web_data
    driver: local